spring:
  profiles: 
    active: 
      - dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-nanaqi-dev      
---      
spring: 
  profiles: test
  application:
    name: microservicecloud-config-nanaqi-test 
# 请保存为 UTF-8格式